# -----------------------------------------------------------------------------
#
# This file is part of the xPack project (http://xpack.github.io).
# Copyright (c) 2025 Liviu Ionescu. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose is hereby granted, under the terms of the MIT license.
#
# If a copy of the license was not distributed with this file, it can
# be obtained from https://opensource.org/licenses/MIT.
#
# -----------------------------------------------------------------------------

  name: 'Test SourceForge downloads'

  on:
    schedule:
      - cron: '42 1 * * 6' # every Sunday
    workflow_dispatch:

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: xpack-dev-tools/xbb-helper-xpack
            ref: 'xpack-development'

        - name: Show environment
          run: |
            ls -lLA
            env | sort | grep -E '^[^ \t]+='

        - name: Run test
          run: |
            #!/usr/bin/env bash
            set -e

            # The script is in the xbb-helper-xpack repo.
            source maintenance-scripts/download-sourceforge-source.sh

            date

            # https://sourceforge.net/projects/aarch64-none-elf-gcc-xpack/files/
            name="aarch64-none-elf-gcc"
            threshold=00000

            download_sourceforge_2025 "${name}" "14.2.1-1.1"  ${threshold}

            download_sourceforge_2023 "${name}" "13.3.1-1.1"  ${threshold}
            download_sourceforge_2023 "${name}" "13.3.1-1.1"  ${threshold}
            download_sourceforge_2023 "${name}" "12.3.1-1.2"  ${threshold}
            download_sourceforge_2023 "${name}" "12.2.1-1.2"  ${threshold}
            download_sourceforge_2023 "${name}" "11.3.1-1.2"  ${threshold}
            download_sourceforge_2023 "${name}" "11.2.1-1.2"  ${threshold}
